pluto_motors:
  # Publish joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel
    pid:
      p: 2.0
      i: 1.0

  # Position Controllers
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel
    pid:
      p: 2.0
      i: 1.0
