pluto_motors:
  # Publish joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  joint1_position_controller:
    type: position_controller/JointPositionController
    joint: A
    pid:
      p: 100.0
      d: 10.0

  # Position Controllers
  joint1_position_controller:
    type: position_controller/JointPositionController
    joint: B
    pid:
      p: 100.0
      d: 10.0
