pluto_motors:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'left_wheel'
    right_wheel: 'right_wheel'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    wheel_separation: 0.4
    wheel_radius: 0.04

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
