TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.25
  max_vel_theta: 0.5
  min_vel_theta: 0.3
  min_in_place_vel_theta: 0.2
  max_in_place_vel_theta: 0.5
  escape_vel: -0.2

  acc_lim_theta: 0.5
  acc_lim_x: 0.1
  acc_lim_y: 0

  holonomic_robot: false

  occdist_scale: 0.02
